### ISSUE TITLE
Display not turning on after turning off the screen

### ISSUE THREAD

**Issue by ghost** [realahnet/treble_voltage#1]
As soon as I pressed the power button to turn the screen off, I wasn't able to turn it on again. After a force reboot, everything worked until I pressed the power button again. Music continued playing, and I was still able to turn on my flashlight using the "chop chop" gesture. I've been facing this issue on many GSI roms including AOSP. There are also a lot of GSIs where this issue isn't present including your YAAP GSI. I hope this can be fixed in this GSI as well.

**Comment by realahnet** [comment]
> As soon as I pressed the power button to turn the screen off, I wasn't able to turn it on again. After a force reboot, everything worked until I pressed the power button again. Music continued playing, and I was still able to turn on my flashlight using the "chop chop" gesture. I've been facing this issue on many GSI roms including AOSP. There are also a lot of GSIs where this issue isn't present including your YAAP GSI. I hope this can be fixed in this GSI as well.

could you provide more context about your device. what device? what firmware. and ensure your on the latest version of voltage. sounds like something source side. i'll see if i have time to look into it.

Also please list the roms that this issue doesnt occur in so i can take a look at any additional patches they might have used

**Comment by ghost** [comment]
My device is Moto G30 (caprip) and is on an unofficial CRdroid 9.8. I tried the latest stock firmware as well and got the same issue. What I forgot to mention: the boot animation was not in the center but in one corner. I faced this issue only on the pixelOS GSI but the lockscreen there worked fine. 
GSIs that don't have the issue:
- crDroid
- ArrowOS 
-  SuperiorOS
- SparkOS
- Lineageos
- RisingOS (latest September security patch)
- YAAP
- pixelOS

**Comment by realahnet** [comment]
> My device is Moto G30 (caprip) and is on an unofficial CRdroid 9.8. I tried the latest stock firmware as well and got the same issue. What I forgot to mention: the boot animation was not in the center but in one corner. I faced this issue only on the pixelOS GSI but the lockscreen there worked fine. GSIs that don't have the issue:
> 
> * crDroid
> * ArrowOS
> * SuperiorOS
> * SparkOS
> * Lineageos
> * RisingOS (latest September security patch)
> * YAAP
> * pixelOS

could you try grabbing logs while trying to wake the device up?

**Comment by realahnet** [comment]
> > My device is Moto G30 (caprip) and is on an unofficial CRdroid 9.8. I tried the latest stock firmware as well and got the same issue. What I forgot to mention: the boot animation was not in the center but in one corner. I faced this issue only on the pixelOS GSI but the lockscreen there worked fine. GSIs that don't have the issue:
> > 
> > * crDroid
> > * ArrowOS
> > * SuperiorOS
> > * SparkOS
> > * Lineageos
> > * RisingOS (latest September security patch)
> > * YAAP
> > * pixelOS
> 
> could you try grabbing logs while trying to wake the device up?

just found out a patch for wakelock issue is missing for some reason. I currently dont have voltage os synced on my computer and it would take a long time to do on my internet. I am sorry but i cant do anything for now. since the next release i'll do is android 14

**Comment by ghost** [comment]
[log.txt](https://github.com/ahnet-69/treble_voltage/files/12794870/log.txt)

This is probably a wakelock issue. When I conected the device to my PC over scrcpy, when I pressed the power button after turning off the screen, I saw the lockscreen for a very short time and then my screen froze in scrcpy.

**Comment by taygunkara** [comment]
I got the same error. My device is Samsung Galaxy A23 SM-A235F.

**Comment by realahnet** [comment]
Will be fixed on android 14 builds hopefully. sorry for the inconvienience
